export enum NotificationEvent {
  ASSET_TRANSFERRED = 'ASSET_TRANSFERRED',
  ASSET_STATUS_CHANGED = 'ASSET_STATUS_CHANGED',
  WORK_ORDER_ASSIGNED = 'WORK_ORDER_ASSIGNED',
  WORK_ORDER_COMPLETED = 'WORK_ORDER_COMPLETED',
  MAINTENANCE_DUE = 'MAINTENANCE_DUE',
  WARRANTY_EXPIRING = 'WARRANTY_EXPIRING',
  CHECKOUT_OVERDUE = 'CHECKOUT_OVERDUE',
  CONTRACT_EXPIRING = 'CONTRACT_EXPIRING',
  LOW_STOCK = 'LOW_STOCK',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
}
