/**
 * contracts/types/assetsup.ts
 *
 * TypeScript bindings for the `assetsup` Soroban contract.
 *
 * Auto-generated by:
 *   stellar contract bindings typescript \
 *     --wasm target/wasm32-unknown-unknown/release/assetsup.wasm \
 *     --network testnet \
 *     --output-dir contracts/types
 *
 * Then manually annotated for clarity. Re-run the above command after any
 * contract change to keep this file in sync with the on-chain ABI.
 *
 * Soroban XDR <-> TypeScript mapping used throughout:
 *   Address    -> string  (G... Stellar public key or C... contract ID)
 *   Bytes      -> Buffer | Uint8Array
 *   BytesN<N>  -> Buffer  (fixed-length N bytes)
 *   String     -> string
 *   Symbol     -> string  (≤ 32 chars, used as enum discriminant)
 *   Map<K,V>   -> Map<K, V>
 *   Vec<T>     -> T[]
 *   bool       -> boolean
 *   u32        -> number
 *   i32        -> number
 *   u64        -> bigint
 *   i64        -> bigint
 *   u128       -> bigint
 *   i128       -> bigint
 *   u256       -> bigint
 *   i256       -> bigint
 *   Option<T>  -> T | null
 */

import {
    Contract,
    SorobanRpc,
    TransactionBuilder,
    Networks,
    BASE_FEE,
    nativeToScVal,
    scValToNative,
    Address,
    xdr,
  } from "@stellar/stellar-sdk";
  
  // ─── Enums ────────────────────────────────────────────────────────────────────
  
  /**
   * Asset condition — mirrors the `AssetCondition` Soroban enum.
   * Stored as a Symbol XDR value on-chain.
   */
  export enum AssetCondition {
    New = "New",
    Good = "Good",
    Fair = "Fair",
    Poor = "Poor",
    Decommissioned = "Decommissioned",
  }
  
  /**
   * Asset status — mirrors the `AssetStatus` Soroban enum.
   */
  export enum AssetStatus {
    Active = "Active",
    Inactive = "Inactive",
    UnderMaintenance = "UnderMaintenance",
    Disposed = "Disposed",
    Lost = "Lost",
  }
  
  // ─── Structs ──────────────────────────────────────────────────────────────────
  
  /**
   * Core asset record stored in contract storage.
   * Mirrors the `Asset` struct in `contracts/assetsup/src/types.rs`.
   */
  export interface Asset {
    /** Unique asset identifier (UUID or internal ID). Soroban type: String */
    id: string;
    /** Human-readable asset name. Soroban type: String */
    name: string;
    /** Asset category (e.g. "IT Equipment", "Furniture"). Soroban type: String */
    category: string;
    /** Manufacturer serial number. Soroban type: String */
    serial_number: string;
    /** Optional free-text description. Soroban type: Option<String> */
    description: string | null;
    /** ID of the department that owns this asset. Soroban type: String */
    department_id: string;
    /** ID of the physical location. Soroban type: String */
    location_id: string;
    /** Stellar address of the assigned user. Soroban type: Address */
    assigned_user_id: string;
    /** ISO-8601 date string of purchase. Soroban type: String */
    purchase_date: string;
    /** Purchase value in stroops (1 XLM = 10_000_000 stroops). Soroban type: i128 */
    purchase_value: bigint;
    /** Current physical condition. Soroban type: Symbol (AssetCondition) */
    condition: AssetCondition;
    /** Lifecycle status. Soroban type: Symbol (AssetStatus) */
    status: AssetStatus;
    /** Ledger timestamp of last update. Soroban type: u64 */
    updated_at: bigint;
    /** Stellar address of the admin that created this record. Soroban type: Address */
    created_by: string;
  }
  
  /**
   * Payload for creating a new asset.
   * All fields are required except `description`.
   */
  export interface CreateAssetPayload {
    name: string;
    category: string;
    serial_number: string;
    description?: string | null;
    department_id: string;
    location_id: string;
    assigned_user_id: string;
    purchase_date: string;
    /** In stroops. Use `BigInt(Math.round(xlmAmount * 1e7))` to convert from XLM. */
    purchase_value: bigint;
    condition: AssetCondition;
    status: AssetStatus;
  }
  
  /**
   * Payload for updating an existing asset.
   * All fields are optional — only provided fields are updated.
   * Mirrors `EditAssetPayload` in the frontend.
   */
  export interface UpdateAssetPayload {
    name?: string;
    category?: string;
    serial_number?: string;
    description?: string | null;
    department_id?: string;
    location_id?: string;
    assigned_user_id?: string;
    purchase_date?: string;
    purchase_value?: bigint;
    condition?: AssetCondition;
    status?: AssetStatus;
  }
  
  /**
   * Paginated list result returned by `list_assets`.
   */
  export interface AssetPage {
    /** Slice of assets for the requested page. */
    items: Asset[];
    /** Total number of assets in storage (for pagination UI). Soroban type: u32 */
    total: number;
  }
  
  // ─── Error codes ──────────────────────────────────────────────────────────────
  
  /**
   * Contract error codes returned as XDR error values.
   * Map these to user-facing messages in the backend.
   */
  export enum AssetsUpError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    Unauthorized = 3,
    AssetNotFound = 4,
    AssetAlreadyExists = 5,
    InvalidInput = 6,
    StorageError = 7,
  }
  
  // ─── Client class ─────────────────────────────────────────────────────────────
  
  export interface AssetsUpClientOptions {
    /** Deployed contract ID (C... address). */
    contractId: string;
    /** RPC server URL. */
    rpcUrl: string;
    /**
     * Network passphrase.
     * Use `Networks.TESTNET` or `Networks.PUBLIC` from @stellar/stellar-sdk.
     */
    networkPassphrase: string;
  }
  
  /**
   * Type-safe client for the `assetsup` Soroban contract.
   *
   * @example
   * ```ts
   * import { AssetsUpClient, AssetCondition, AssetStatus } from "./types/assetsup";
   * import { Networks } from "@stellar/stellar-sdk";
   *
   * const client = new AssetsUpClient({
   *   contractId: process.env.ASSETSUP_CONTRACT_ID!,
   *   rpcUrl: "https://soroban-testnet.stellar.org",
   *   networkPassphrase: Networks.TESTNET,
   * });
   *
   * const asset = await client.getAsset("asset-001");
   * ```
   */
  export class AssetsUpClient {
    private readonly contract: Contract;
    private readonly server: SorobanRpc.Server;
    private readonly networkPassphrase: string;
  
    constructor(opts: AssetsUpClientOptions) {
      this.contract = new Contract(opts.contractId);
      this.server = new SorobanRpc.Server(opts.rpcUrl);
      this.networkPassphrase = opts.networkPassphrase;
    }
  
    // ── Read-only calls (simulation only) ──────────────────────────────────────
  
    /**
     * Fetch a single asset by ID.
     *
     * Soroban function: `get_asset(id: String) -> Asset`
     * Access: Public (anyone can call)
     *
     * @throws {AssetsUpError.AssetNotFound} if the ID does not exist
     */
    async getAsset(id: string): Promise<Asset> {
      const operation = this.contract.call(
        "get_asset",
        nativeToScVal(id, { type: "string" })
      );
      const result = await this.simulateOperation(operation);
      return scValToNative(result) as Asset;
    }
  
    /**
     * List assets with optional pagination.
     *
     * Soroban function: `list_assets(page: u32, page_size: u32) -> AssetPage`
     * Access: Public
     *
     * @param page       Zero-based page index (default 0)
     * @param pageSize   Number of records per page, max 100 (default 20)
     */
    async listAssets(page = 0, pageSize = 20): Promise<AssetPage> {
      const operation = this.contract.call(
        "list_assets",
        nativeToScVal(page, { type: "u32" }),
        nativeToScVal(pageSize, { type: "u32" })
      );
      const result = await this.simulateOperation(operation);
      return scValToNative(result) as AssetPage;
    }
  
    /**
     * Query assets assigned to a specific user.
     *
     * Soroban function: `get_assets_by_user(user: Address) -> Vec<Asset>`
     * Access: Public
     */
    async getAssetsByUser(userAddress: string): Promise<Asset[]> {
      const operation = this.contract.call(
        "get_assets_by_user",
        new Address(userAddress).toScVal()
      );
      const result = await this.simulateOperation(operation);
      return scValToNative(result) as Asset[];
    }
  
    /**
     * Query assets in a given department.
     *
     * Soroban function: `get_assets_by_department(department_id: String) -> Vec<Asset>`
     * Access: Public
     */
    async getAssetsByDepartment(departmentId: string): Promise<Asset[]> {
      const operation = this.contract.call(
        "get_assets_by_department",
        nativeToScVal(departmentId, { type: "string" })
      );
      const result = await this.simulateOperation(operation);
      return scValToNative(result) as Asset[];
    }
  
    /**
     * Return the current admin address.
     *
     * Soroban function: `get_admin() -> Address`
     * Access: Public
     */
    async getAdmin(): Promise<string> {
      const operation = this.contract.call("get_admin");
      const result = await this.simulateOperation(operation);
      return scValToNative(result) as string;
    }
  
    // ── Write calls (require signing) ──────────────────────────────────────────
  
    /**
     * Build a `create_asset` transaction for signing.
     *
     * Soroban function: `create_asset(caller: Address, payload: CreateAssetPayload) -> String`
     * Returns: the newly created asset ID
     * Access: Admin only
     *
     * @example
     * ```ts
     * const txXdr = await client.buildCreateAsset(callerKeypair.publicKey(), payload);
     * // Sign and submit with your Keypair or wallet
     * const signedTx = txXdr.sign(callerKeypair);
     * await server.sendTransaction(signedTx);
     * ```
     */
    async buildCreateAsset(
      callerAddress: string,
      payload: CreateAssetPayload,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const operation = this.contract.call(
        "create_asset",
        new Address(callerAddress).toScVal(),
        nativeToScVal(payload)
      );
      return this.buildTransaction(operation, sourceAccount);
    }
  
    /**
     * Build an `update_asset` transaction for signing.
     *
     * Soroban function: `update_asset(caller: Address, id: String, payload: UpdateAssetPayload) -> Asset`
     * Returns: the updated Asset record
     * Access: Admin only
     */
    async buildUpdateAsset(
      callerAddress: string,
      assetId: string,
      payload: UpdateAssetPayload,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const operation = this.contract.call(
        "update_asset",
        new Address(callerAddress).toScVal(),
        nativeToScVal(assetId, { type: "string" }),
        nativeToScVal(payload)
      );
      return this.buildTransaction(operation, sourceAccount);
    }
  
    /**
     * Build a `delete_asset` transaction for signing.
     *
     * Soroban function: `delete_asset(caller: Address, id: String) -> bool`
     * Returns: true on success
     * Access: Admin only
     */
    async buildDeleteAsset(
      callerAddress: string,
      assetId: string,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const operation = this.contract.call(
        "delete_asset",
        new Address(callerAddress).toScVal(),
        nativeToScVal(assetId, { type: "string" })
      );
      return this.buildTransaction(operation, sourceAccount);
    }
  
    /**
     * Build an `upgrade` transaction (admin-only, used by upgrade-contract.sh).
     *
     * Soroban function: `upgrade(new_wasm_hash: BytesN<32>) -> ()`
     * Access: Admin only
     */
    async buildUpgrade(
      newWasmHash: Buffer,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const operation = this.contract.call(
        "upgrade",
        xdr.ScVal.scvBytes(newWasmHash)
      );
      return this.buildTransaction(operation, sourceAccount);
    }
  
    // ── Private helpers ─────────────────────────────────────────────────────────
  
    private async simulateOperation(
      operation: xdr.Operation
    ): Promise<xdr.ScVal> {
      const account = await this.server.getAccount(
        // Use a burn address for read-only simulations
        "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN"
      );
      const tx = new TransactionBuilder(account, {
        fee: BASE_FEE,
        networkPassphrase: this.networkPassphrase,
      })
        .addOperation(operation)
        .setTimeout(30)
        .build();
  
      const simResult = await this.server.simulateTransaction(tx);
      if (SorobanRpc.Api.isSimulationError(simResult)) {
        throw new Error(`Simulation failed: ${simResult.error}`);
      }
      if (!simResult.result) {
        throw new Error("Simulation returned no result.");
      }
      return simResult.result.retval;
    }
  
    private async buildTransaction(
      operation: xdr.Operation,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      return new TransactionBuilder(sourceAccount, {
        fee: BASE_FEE,
        networkPassphrase: this.networkPassphrase,
      })
        .addOperation(operation)
        .setTimeout(30);
    }
  }