/**
 * contracts/types/multisig_transfer.ts
 *
 * TypeScript bindings for the `multisig_transfer` Soroban contract.
 *
 * Auto-generated by:
 *   stellar contract bindings typescript \
 *     --wasm target/wasm32-unknown-unknown/release/multisig_transfer.wasm \
 *     --network testnet \
 *     --output-dir contracts/types
 *
 * Then manually annotated for clarity. Re-run the above command after any
 * contract change to keep this file in sync with the on-chain ABI.
 *
 * XDR <-> TypeScript mapping: see assetsup.ts header for the full table.
 */

import {
    Contract,
    SorobanRpc,
    TransactionBuilder,
    Networks,
    BASE_FEE,
    nativeToScVal,
    scValToNative,
    Address,
    xdr,
  } from "@stellar/stellar-sdk";
  
  // ─── Enums ────────────────────────────────────────────────────────────────────
  
  /**
   * Lifecycle state of a transfer proposal.
   * Mirrors `TransferStatus` in `contracts/multisig_transfer/src/types.rs`.
   */
  export enum TransferStatus {
    /** Proposal created, awaiting signatures. */
    Pending = "Pending",
    /** Enough signers have approved — transfer can be executed. */
    Approved = "Approved",
    /** Transfer has been executed on-chain. */
    Executed = "Executed",
    /** Proposal was rejected (threshold of rejections met, or admin cancelled). */
    Rejected = "Rejected",
    /** Proposal expired without reaching the signature threshold. */
    Expired = "Expired",
  }
  
  /**
   * A signer's decision on a transfer proposal.
   */
  export enum SignerDecision {
    Approve = "Approve",
    Reject = "Reject",
  }
  
  // ─── Structs ──────────────────────────────────────────────────────────────────
  
  /**
   * A single signer entry within a multisig transfer proposal.
   */
  export interface SignerEntry {
    /** Stellar address of the signer. Soroban type: Address */
    address: string;
    /** Whether they have signed. Soroban type: bool */
    has_signed: boolean;
    /** Their decision, if signed. Soroban type: Option<Symbol (SignerDecision)> */
    decision: SignerDecision | null;
    /** Ledger timestamp of signature. Soroban type: Option<u64> */
    signed_at: bigint | null;
  }
  
  /**
   * A multi-signature asset transfer proposal.
   * Mirrors `TransferProposal` in `contracts/multisig_transfer/src/types.rs`.
   */
  export interface TransferProposal {
    /** Unique proposal ID. Soroban type: String */
    id: string;
    /** The asset being transferred. Soroban type: String */
    asset_id: string;
    /** Current holder of the asset. Soroban type: Address */
    from_user: string;
    /** Intended new holder of the asset. Soroban type: Address */
    to_user: string;
    /** Optional transfer notes / reason. Soroban type: Option<String> */
    notes: string | null;
    /** Minimum number of approvals required. Soroban type: u32 */
    required_signatures: number;
    /** All signers and their current state. Soroban type: Vec<SignerEntry> */
    signers: SignerEntry[];
    /** Current proposal status. Soroban type: Symbol (TransferStatus) */
    status: TransferStatus;
    /** Ledger timestamp when proposal was created. Soroban type: u64 */
    created_at: bigint;
    /** Ledger timestamp after which the proposal expires. Soroban type: u64 */
    expires_at: bigint;
    /** Ledger timestamp when executed (if applicable). Soroban type: Option<u64> */
    executed_at: bigint | null;
    /** Address that created this proposal. Soroban type: Address */
    proposed_by: string;
  }
  
  /**
   * Payload to create a new transfer proposal.
   */
  export interface CreateTransferPayload {
    /** ID of the asset to transfer (must exist in the assetsup contract). */
    asset_id: string;
    /** Address of the current asset holder. */
    from_user: string;
    /** Address of the intended recipient. */
    to_user: string;
    /** Optional description/reason for the transfer. */
    notes?: string | null;
    /** Number of approvals needed (must be ≤ signers.length). */
    required_signatures: number;
    /** Addresses of signers who must approve. */
    signers: string[];
    /**
     * Ledger timestamp (seconds since Unix epoch) when proposal expires.
     * Use `Date.now() / 1000 + 86400` for a 24-hour expiry.
     */
    expires_at: bigint;
  }
  
  /**
   * Summary counters returned by `get_proposal_stats`.
   */
  export interface ProposalStats {
    /** Total proposals ever created. Soroban type: u32 */
    total: number;
    /** Currently pending proposals. Soroban type: u32 */
    pending: number;
    /** Proposals in Approved state (not yet executed). Soroban type: u32 */
    approved: number;
    /** Proposals successfully executed. Soroban type: u32 */
    executed: number;
    /** Proposals that were rejected or expired. Soroban type: u32 */
    rejected: number;
  }
  
  // ─── Error codes ──────────────────────────────────────────────────────────────
  
  export enum MultisigTransferError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    Unauthorized = 3,
    ProposalNotFound = 4,
    ProposalAlreadyExists = 5,
    ProposalNotPending = 6,
    SignerNotFound = 7,
    AlreadySigned = 8,
    InsufficientSignatures = 9,
    ProposalExpired = 10,
    InvalidInput = 11,
  }
  
  // ─── Client class ─────────────────────────────────────────────────────────────
  
  export interface MultisigTransferClientOptions {
    contractId: string;
    rpcUrl: string;
    networkPassphrase: string;
  }
  
  /**
   * Type-safe client for the `multisig_transfer` Soroban contract.
   *
   * @example
   * ```ts
   * import { MultisigTransferClient, TransferStatus } from "./types/multisig_transfer";
   * import { Networks } from "@stellar/stellar-sdk";
   *
   * const client = new MultisigTransferClient({
   *   contractId: process.env.MULTISIG_TRANSFER_CONTRACT_ID!,
   *   rpcUrl: "https://soroban-testnet.stellar.org",
   *   networkPassphrase: Networks.TESTNET,
   * });
   *
   * const proposals = await client.listProposalsByAsset("asset-001");
   * ```
   */
  export class MultisigTransferClient {
    private readonly contract: Contract;
    private readonly server: SorobanRpc.Server;
    private readonly networkPassphrase: string;
  
    constructor(opts: MultisigTransferClientOptions) {
      this.contract = new Contract(opts.contractId);
      this.server = new SorobanRpc.Server(opts.rpcUrl);
      this.networkPassphrase = opts.networkPassphrase;
    }
  
    // ── Read-only calls ────────────────────────────────────────────────────────
  
    /**
     * Fetch a single transfer proposal by ID.
     *
     * Soroban function: `get_proposal(id: String) -> TransferProposal`
     * Access: Public
     *
     * @throws {MultisigTransferError.ProposalNotFound}
     */
    async getProposal(id: string): Promise<TransferProposal> {
      const op = this.contract.call(
        "get_proposal",
        nativeToScVal(id, { type: "string" })
      );
      const result = await this.simulateOperation(op);
      return scValToNative(result) as TransferProposal;
    }
  
    /**
     * List all proposals for a given asset.
     *
     * Soroban function: `list_proposals_by_asset(asset_id: String) -> Vec<TransferProposal>`
     * Access: Public
     */
    async listProposalsByAsset(assetId: string): Promise<TransferProposal[]> {
      const op = this.contract.call(
        "list_proposals_by_asset",
        nativeToScVal(assetId, { type: "string" })
      );
      const result = await this.simulateOperation(op);
      return scValToNative(result) as TransferProposal[];
    }
  
    /**
     * List all proposals where the given user is a required signer.
     *
     * Soroban function: `list_proposals_for_signer(signer: Address) -> Vec<TransferProposal>`
     * Access: Public
     */
    async listProposalsForSigner(signerAddress: string): Promise<TransferProposal[]> {
      const op = this.contract.call(
        "list_proposals_for_signer",
        new Address(signerAddress).toScVal()
      );
      const result = await this.simulateOperation(op);
      return scValToNative(result) as TransferProposal[];
    }
  
    /**
     * Get aggregate proposal statistics.
     *
     * Soroban function: `get_proposal_stats() -> ProposalStats`
     * Access: Public
     */
    async getProposalStats(): Promise<ProposalStats> {
      const op = this.contract.call("get_proposal_stats");
      const result = await this.simulateOperation(op);
      return scValToNative(result) as ProposalStats;
    }
  
    /**
     * Check whether a specific signer has signed a proposal.
     *
     * Soroban function: `has_signed(proposal_id: String, signer: Address) -> bool`
     * Access: Public
     */
    async hasSigned(proposalId: string, signerAddress: string): Promise<boolean> {
      const op = this.contract.call(
        "has_signed",
        nativeToScVal(proposalId, { type: "string" }),
        new Address(signerAddress).toScVal()
      );
      const result = await this.simulateOperation(op);
      return scValToNative(result) as boolean;
    }
  
    // ── Write calls (require signing) ──────────────────────────────────────────
  
    /**
     * Build a `create_proposal` transaction for signing.
     *
     * Soroban function: `create_proposal(caller: Address, payload: CreateTransferPayload) -> String`
     * Returns: the newly created proposal ID
     * Access: Admin or authorised user
     *
     * @example
     * ```ts
     * const txBuilder = await client.buildCreateProposal(
     *   keypair.publicKey(),
     *   {
     *     asset_id: "asset-001",
     *     from_user: "GABC...",
     *     to_user: "GXYZ...",
     *     required_signatures: 2,
     *     signers: ["GABC...", "GDEF...", "GHIJ..."],
     *     expires_at: BigInt(Math.floor(Date.now() / 1000) + 86400),
     *   },
     *   sourceAccount
     * );
     * const tx = txBuilder.build();
     * tx.sign(keypair);
     * await server.sendTransaction(tx);
     * ```
     */
    async buildCreateProposal(
      callerAddress: string,
      payload: CreateTransferPayload,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const op = this.contract.call(
        "create_proposal",
        new Address(callerAddress).toScVal(),
        nativeToScVal(payload)
      );
      return this.buildTransaction(op, sourceAccount);
    }
  
    /**
     * Build a `sign_proposal` transaction for signing.
     *
     * Soroban function: `sign_proposal(signer: Address, proposal_id: String, decision: Symbol) -> TransferProposal`
     * Returns: updated TransferProposal
     * Access: Must be one of the listed signers on the proposal
     *
     * @throws {MultisigTransferError.SignerNotFound}
     * @throws {MultisigTransferError.AlreadySigned}
     * @throws {MultisigTransferError.ProposalExpired}
     */
    async buildSignProposal(
      signerAddress: string,
      proposalId: string,
      decision: SignerDecision,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const op = this.contract.call(
        "sign_proposal",
        new Address(signerAddress).toScVal(),
        nativeToScVal(proposalId, { type: "string" }),
        nativeToScVal(decision, { type: "symbol" })
      );
      return this.buildTransaction(op, sourceAccount);
    }
  
    /**
     * Build an `execute_transfer` transaction for signing.
     *
     * Soroban function: `execute_transfer(caller: Address, proposal_id: String) -> TransferProposal`
     * Returns: final executed TransferProposal
     * Access: Admin or the proposal initiator, only when status is Approved
     *
     * @throws {MultisigTransferError.InsufficientSignatures}
     * @throws {MultisigTransferError.ProposalNotPending}
     */
    async buildExecuteTransfer(
      callerAddress: string,
      proposalId: string,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const op = this.contract.call(
        "execute_transfer",
        new Address(callerAddress).toScVal(),
        nativeToScVal(proposalId, { type: "string" })
      );
      return this.buildTransaction(op, sourceAccount);
    }
  
    /**
     * Build a `cancel_proposal` transaction for signing.
     *
     * Soroban function: `cancel_proposal(caller: Address, proposal_id: String) -> bool`
     * Returns: true on success
     * Access: Admin only
     */
    async buildCancelProposal(
      callerAddress: string,
      proposalId: string,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const op = this.contract.call(
        "cancel_proposal",
        new Address(callerAddress).toScVal(),
        nativeToScVal(proposalId, { type: "string" })
      );
      return this.buildTransaction(op, sourceAccount);
    }
  
    /**
     * Build an `upgrade` transaction (admin-only).
     *
     * Soroban function: `upgrade(new_wasm_hash: BytesN<32>) -> ()`
     * Access: Admin only
     */
    async buildUpgrade(
      newWasmHash: Buffer,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      const op = this.contract.call("upgrade", xdr.ScVal.scvBytes(newWasmHash));
      return this.buildTransaction(op, sourceAccount);
    }
  
    // ── Private helpers ─────────────────────────────────────────────────────────
  
    private async simulateOperation(op: xdr.Operation): Promise<xdr.ScVal> {
      const account = await this.server.getAccount(
        "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN"
      );
      const tx = new TransactionBuilder(account, {
        fee: BASE_FEE,
        networkPassphrase: this.networkPassphrase,
      })
        .addOperation(op)
        .setTimeout(30)
        .build();
  
      const simResult = await this.server.simulateTransaction(tx);
      if (SorobanRpc.Api.isSimulationError(simResult)) {
        throw new Error(`Simulation failed: ${simResult.error}`);
      }
      if (!simResult.result) {
        throw new Error("Simulation returned no result.");
      }
      return simResult.result.retval;
    }
  
    private async buildTransaction(
      op: xdr.Operation,
      sourceAccount: SorobanRpc.Api.GetAccountResponse
    ): Promise<TransactionBuilder> {
      return new TransactionBuilder(sourceAccount, {
        fee: BASE_FEE,
        networkPassphrase: this.networkPassphrase,
      })
        .addOperation(op)
        .setTimeout(30);
    }
  }